PROG = 7zCon.sfx

# IS_X64 = 1
# USE_ASM = 1
# ST_MODE = 1

include ../../LzmaDec_gcc.mak


LOCAL_FLAGS_ST =
MT_OBJS = \


ifdef SystemDrive
IS_MINGW = 1
else
ifdef SYSTEMDRIVE
# ifdef OS
IS_MINGW = 1
endif
endif

ifdef ST_MODE

LOCAL_FLAGS_ST = -DZ7_ST

ifdef IS_MINGW
MT_OBJS = \
  $O/Threads.o \

endif

else

MT_OBJS = \
  $O/StreamBinder.o \
  $O/Synchronization.o \
  $O/VirtThread.o \
  $O/Threads.o \
  $O/LzFindMt.o \
  $O/LzFindOpt.o \
  $O/MemBlocks.o \
  $O/OutMemStream.o \
  $O/ProgressMt.o \

endif



LOCAL_FLAGS_SYS =

ifdef IS_MINGW

LOCAL_FLAGS_SYS = \
  -DZ7_NO_LONG_PATH \
  -DZ7_NO_LARGE_PAGES \

SYS_OBJS = \
  $O/DLL.o \
  $O/DllSecur.o \
  $O/resource.o \

else

SYS_OBJS = \
  $O/MyWindows.o \

endif



LOCAL_FLAGS = \
  -DZ7_EXTRACT_ONLY \
  -DZ7_NO_READ_FROM_CODER \
  -DZ7_SFX \
  $(LOCAL_FLAGS_ST) \
  $(LOCAL_FLAGS_SYS) \


CURRENT_OBJS = \
  $O/SfxCon.o \

CONSOLE_OBJS = \
  $O/ConsoleClose.o \
  $O/ExtractCallbackConsole.o \
  $O/List.o \
  $O/MainAr.o \
  $O/OpenCallbackConsole.o \
  $O/PercentPrinter.o \
  $O/UserInputUtils.o \

COMMON_OBJS = \
  $O/CommandLineParser.o \
  $O/CRC.o \
  $O/IntToString.o \
  $O/MyString.o \
  $O/MyVector.o \
  $O/StdInStream.o \
  $O/StdOutStream.o \
  $O/StringConvert.o \
  $O/Wildcard.o \
  $O/Sha1Prepare.o \
  $O/Sha1Reg.o \
  $O/Sha256Prepare.o \
  $O/Sha256Reg.o \
  $O/Sha3Reg.o \
  $O/Sha512Prepare.o \
  $O/Sha512Reg.o \
  $O/StringToInt.o \
  $O/UTFConvert.o \
  $O/Xxh64Reg.o \

WIN_OBJS = \
  \
  $O/ErrorMsg.o \
  $O/FileDir.o \
  $O/FileFind.o \
  $O/FileIO.o \
  $O/FileName.o \
  $O/PropVariant.o \
  $O/PropVariantConv.o \
  \
  $O/System.o \
  $O/TimeUtils.o \

7ZIP_COMMON_OBJS = \
  $O/CreateCoder.o \
  $O/CWrappers.o \
  $O/FilePathAutoRename.o \
  $O/FileStreams.o \
  $O/InBuffer.o \
  $O/FilterCoder.o \
  $O/LimitedStreams.o \
  $O/OutBuffer.o \
  $O/ProgressUtils.o \
  $O/PropId.o \
  \
  $O/StreamObjects.o \
  $O/StreamUtils.o \
  \

UI_COMMON_OBJS = \
  $O/ArchiveExtractCallback.o \
  $O/ArchiveOpenCallback.o \
  $O/DefaultName.o \
  $O/Extract.o \
  $O/ExtractingFilePath.o \
  $O/LoadCodecs.o \
  $O/OpenArchive.o \
  $O/PropIDUtils.o \

AR_OBJS = \
  $O/SplitHandler.o \

AR_COMMON_OBJS = \
  $O/CoderMixer2.o \
  $O/ItemNameUtils.o \
  $O/MultiStream.o \
  $O/OutStreamWithCRC.o \

7Z_OBJS = \
  $O/7zDecode.o \
  $O/7zExtract.o \
  $O/7zHandler.o \
  $O/7zIn.o \
  $O/7zRegister.o \

COMPRESS_OBJS = \
  $O/Bcj2Coder.o \
  $O/Bcj2Register.o \
  $O/BcjCoder.o \
  $O/BcjRegister.o \
  $O/BitlDecoder.o \
  $O/ByteSwap.o \
  $O/BZip2Crc.o \
  $O/BZip2Decoder.o \
  $O/BZip2Encoder.o \
  $O/BZip2Register.o \
  $O/CopyCoder.o \
  $O/CopyRegister.o \
  $O/Deflate64Register.o \
  $O/DeflateDecoder.o \
  $O/DeflateEncoder.o \
  $O/DeflateRegister.o \
  $O/DeltaFilter.o \
  $O/ImplodeDecoder.o \
  $O/LzfseDecoder.o \
  $O/LzhDecoder.o \
  $O/Lzma2Decoder.o \
  $O/Lzma2Encoder.o \
  $O/Lzma2Register.o \
  $O/LzmaDecoder.o \
  $O/LzmaEncoder.o \
  $O/LzmaRegister.o \
  $O/LzmsDecoder.o \
  $O/LzOutWindow.o \
  $O/LzxDecoder.o \
  $O/PpmdDecoder.o \
  $O/PpmdEncoder.o \
  $O/PpmdRegister.o \
  $O/PpmdZip.o \
  $O/QuantumDecoder.o \
  $O/ShrinkDecoder.o \
  $O/XpressDecoder.o \
  $O/ZlibDecoder.o \
  $O/ZlibEncoder.o \
  $O/ZDecoder.o \
  $O/ZstdDecoder.o \
  $O/ZstdEncoder.o \
  $O/ZstdRegister.o \
  $O/Lz4Decoder.o \
  $O/Lz4Encoder.o \
  $O/Lz4Register.o \
  $O/BrotliDecoder.o \
  $O/BrotliEncoder.o \
  $O/BrotliRegister.o \
  $O/LizardDecoder.o \
  $O/LizardEncoder.o \
  $O/LizardRegister.o \
  $O/Lz5Decoder.o \
  $O/Lz5Encoder.o \
  $O/Lz5Register.o \
  $O/LzhamRegister.o \

ADDITIONAL_CODECS_OBJS = \
  $O/lz4-mt_common.o \
  $O/lz4-mt_compress.o \
  $O/lz4-mt_decompress.o \
  $O/brotli-mt_common.o \
  $O/brotli-mt_compress.o \
  $O/brotli-mt_decompress.o \
  $O/lizard-mt_common.o \
  $O/lizard-mt_compress.o \
  $O/lizard-mt_decompress.o \
  $O/lz5-mt_common.o \
  $O/lz5-mt_compress.o \
  $O/lz5-mt_decompress.o \
  $O/threading.o \
  $O/lz4.o \
  $O/lz4hc.o \
  $O/lz4frame.o \
  $O/xxhash.o \
  $O/lz5.o \
  $O/lz5hc.o \
  $O/lz5frame.o \
  $O/lizard_compress.o \
  $O/lizard_decompress.o \
  $O/lizard_frame.o \

CRYPTO_OBJS = \
  $O/7zAes.o \
  $O/7zAesRegister.o \
  $O/MyAes.o \

C_OBJS = \
  $O/7zBuf2.o \
  $O/7zCrc.o \
  $O/7zCrcOpt.o \
  $O/7zStream.o \
  $O/Aes.o \
  $O/AesOpt.o \
  $O/Alloc.o \
  $O/Bcj2.o \
  $O/Bcj2Enc.o \
  $O/Blake2s.o \
  $O/Bra.o \
  $O/Bra86.o \
  $O/BraIA64.o \
  $O/BwtSort.o \
  $O/CpuArch.o \
  $O/Delta.o \
  $O/HuffEnc.o \
  $O/LzFind.o \
  $O/Lzma2Dec.o \
  $O/Lzma2DecMt.o \
  $O/Lzma2Enc.o \
  $O/LzmaDec.o \
  $O/LzmaEnc.o \
  $O/Md5.o \
  $O/MtCoder.o \
  $O/MtDec.o \
  $O/Ppmd7.o \
  $O/Ppmd7Dec.o \
  $O/Ppmd7aDec.o \
  $O/Ppmd7Enc.o \
  $O/Ppmd8.o \
  $O/Ppmd8Dec.o \
  $O/Ppmd8Enc.o \
  $O/Sha1.o \
  $O/Sha1Opt.o \
  $O/Sha256.o \
  $O/Sha256Opt.o \
  $O/Sha3.o \
  $O/Sha512.o \
  $O/Sha512Opt.o \
  $O/Sort.o \
  $O/SwapBytes.o \
  $O/Xxh64.o \
  $O/ZstdDec.o \

ZSTD_STATIC_LIB = $O/libzstd.a
# LZ4_STATIC_LIB = $O/liblz4.a
BROTLI_STATIC_LIB = $O/libbrotlienc-static.a \
  $O/libbrotlidec-static.a \
  $O/libbrotlicommon-static.a
# LIZARD_STATIC_LIB = $O/liblizard.a
# LZ5_STATIC_LIB = $O/liblz5.a
LZHAM_STATIC_LIB = $O/lzham_lib.o $O/liblzhamcomp.a $O/liblzhamdecomp.a

HASHES_OBJS = \
  $O/Md2Reg.o \
  $O/Md4Reg.o \
  $O/XXH32Reg.o \
  $O/Blake3Reg.o \
  $O/md2.o \
  $O/md4.o \
  $O/blake3.o \

ifndef DISABLE_PKIMPLODE_COMPRESS
PKIMPLODE_OBJS += \
  $O/PKImplodeDecoder.o \
  $O/PKImplodeEncoder.o \
  $O/PKImplodeRegister.o \
  $O/explode.o \
  $O/implode.o \

endif

FASTLZMA2_OBJS = \
  $O/FastLzma2Register.o \
  $O/FastLzma2Encoder.o \
  $O/dict_buffer.o \
  $O/fl2_common.o \
  $O/fl2_compress.o \
  $O/fl2_pool.o \
  $O/fl2_threading.o \
  $O/lzma2_enc.o \
  $O/radix_bitpack.o \
  $O/radix_mf.o \
  $O/radix_struct.o \
  $O/range_enc.o \
  $O/fl2util.o \

OBJS = \
  $(LZMA_DEC_OPT_OBJS) \
  $(C_OBJS) \
  $(MT_OBJS) \
  $(SYS_OBJS) \
  $(COMMON_OBJS) \
  $(WIN_OBJS) \
  $(COMPRESS_OBJS) \
  $(CRYPTO_OBJS) \
  $(ADDITIONAL_CODECS_OBJS) \
  $(7ZIP_COMMON_OBJS) \
  $(AR_OBJS) \
  $(AR_COMMON_OBJS) \
  $(7Z_OBJS) \
  $(UI_COMMON_OBJS) \
  $(CONSOLE_OBJS) \
  $(CURRENT_OBJS) \
  $(HASHES_OBJS) \
  $(PKIMPLODE_OBJS) \
  $(FASTLZMA2_OBJS) \
  $(ZSTD_STATIC_LIB) \
  $(BROTLI_STATIC_LIB) \
  $(LZHAM_STATIC_LIB) \


include ../../7zip_gcc.mak

